openapi: 3.0.4
info:
  title: Payment Blocker API
  version: 1.0.0
servers:
  - url: http://loсalhost:8080/app/blocker/api
paths:
  /clients/{clientId}/blocks:
    post:
      summary: Создать блокировку клиента.
       Переводит клиента в статус BLOCKED или TEMPORARILY_BLOCKED
      parameters:
        - name: clientId
          in: path
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema: 
              $ref: '#/components/schemas/CreateBlockRequest'
      responses:
        '201':
          description: Клиент заблокирован
          content:
            application/json:
              schema: 
                $ref: '#/components/schemas/Block'
        '400':
          description: Указанная причина блокировки не найдена
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '404' :
          description: Клиент не найден
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '409': 
          description: Клиент уже заблокирован
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
    delete:
      summary: Разблокировать клиента
      parameters:
        - name: clientId
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Клиент разблокирован
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Block'
        '404':
          description: Клиент не найден
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '409':
          description: Клиент не заблокирован
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
    get:
      summary: Получить историю блокировок клиента
      description: Возвращает информацию о клиенте и список всех его блокировок
      parameters:
        - name: clientId
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: История блокировок клиента
          content:
            application/json:
              schema:
                type: object
                properties:
                  client:
                    $ref: '#/components/schemas/ClientStatus'
                  blocks:
                    type: array
                    description: Список всех блокировок клиента
                    items:
                      $ref: '#/components/schemas/BlockInfo'
        '404':
          description: Клиент не найден
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  /clients/{clientId}/block-status:
    get:
      summary: Проверить статус клиента
      parameters:
        - name: clientId
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Статус клиента
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ClientWithBlock'
        '404':
          description: Клиент не найден
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  
components:
  schemas:
    CreateBlockRequest:
      type: object
      description: 'Добавление блокировки'
      required: 
       - reason_code
       - temporary
      properties:
        reason_code:
          type: string
          description: Код причины блокировки
        action:
          type: string
          description: Отклонить все активные платежи клиента или временно приостановить
          enum: [REJECT, HOLD]
        details:
          type: object
          description: Дополнительные данные о блокировке (JSON)
          additionalProperties: true
    Block:
      type: object
      properties:
        client_id:
          type: string
          format: uuid
        status:
          type: string
          enum: [TEMPORARILY_BLOCKED, BLOCKED]
        reason_code:
          type: string
        description:
          type: string
        created_at:
          type: string
          format: date-time
        details:
          type: object
          additionalProperties: true
    ErrorResponse:
      type: object
      required: 
        - error_code
        - message
      properties:
        error_code:
          type: string
          description: Код ошибки
          example: 404 NOT FOUND
        message:
          type: string
          description: Cообщение c указанием ошибки
          example: Клиент с указанным идентификатором не найден
        details:
          type: object
          additionalProperties: true
    ClientStatus:
      type: object
      description: Основная информация о текущем статусе клиенте
      required: 
        - client_id
        - status
      properties:
        client_id:
          type: string
          format: uuid
          description: Идентификатор клиента
        status:
          type: string
          description: Текущий статус клиента
          enum: [CREATED, ACTIVE, TEMPORARILY_BLOCKED, BLOCKED, CLOSED]
        set_at:
          type: string
          format: date-time
        set_by:
          type: string
          nullable: true
    BlockInfo:
      type: object
      description: Информация о текущей блокировке клиента
      properties:
        reason_code:
          type: string
          description: Код причины блокировки
        description:
          type: string
          description: Описание причины блокировки
        created_at:
          type: string
          format: date-time
          description: Время создания блокировки
        created_by:
          type: string
          description: Источник или инициатор создания блокировки. Например, "MONITORING SYSTEM" — автоматическая блокировка системой мониторинга, "MANUAL" — блокировка выполнена вручную оператором.
        released_at:
          type: string
          format: date-time
          description: Время снятия блокировки
          nullable: true
        released_by:
          type: string
          description: Источник или инициатор снятия блокировки
          nullable: true
    ClientWithBlock:
      type: object
      description: Информация о статусе клиента и его последней блокировке
      properties:
        client:
          $ref: '#/components/schemas/ClientStatus'
        block:
          nullable: true
          $ref: '#/components/schemas/BlockInfo'
                
